### ISSUE TITLE
urxvt ranger crashes when opening image preview

### ISSUE THREAD

**Issue by PhilipNelson5** [ranger/ranger#1053]
#### Runtime Environment

- Operating system and version: Fresh install of Manjaro I3
- Terminal emulator and version: xrvt-unicode-pixbuf
- Python version: 3.6
- Ranger version/commit: 1.9.0-1

#### Steps Taken to Resolve
I installed xrvt-unicode-pixbuf and the same crashing behavior persists. 
#### Current Behavior
If I navigate to an image, ranger crashes

#### Expected Behavior
ranger should display the image preview

#### Context

I was trying to get image preview to work. This is a fresh install of Manjaro i3. Ranger comes installed.

#### Steps to reproduce
1. Open ranger
2. navigate to image
3. move to image
4. crash

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character

```

**Comment by keithnyc** [comment]
This also happens on kitty and terminology emulators. Also testing on a fresh manjaro i3 install.

**Comment by comraderayane** [comment]
I'm also getting this issue with the latest git clone (bfe1dba), python 3.6.4, and Arch Linux

**Comment by 4q4q5e1e** [comment]
Same here, i get this crash not only trying to preview images but hovering over my .Xauthority file.

**Comment by lanxu** [comment]
I encountered this error too. I fixed the problem by catching ValueError in addstr()/addnstr() methods in curses_shortcuts.py.

**Comment by PhilipNelson5** [comment]
That fixed the crashing problem, however I still do not get an image preview

I am using rxvt-unicode-pixpuf and these options in my rc.conf

```
# Which script is used to generate file previews?
set preview_script ~/.config/ranger/scope.sh

# Use the external preview script or display simple plain text or image previews?
set use_preview_script true

# Use one of the supported image preview protocols
set preview_images true

set preview_images_method urxvt
```
This is the result

![picture](https://user-images.githubusercontent.com/19827319/36082640-8b014bda-0f68-11e8-9f6c-c0b3f03aeb1c.png)

**Comment by toonn** [comment]
@PhilipNelson5 How old is your `scope.sh` or did you customize it? The current one doesn't have this cp command in it and [line 77](https://github.com/ranger/ranger/blob/0b4f6b2a1ef5a3955835a6cfd9a0686abf6d0a23/ranger/data/scope.sh#L77) is blank.

If everyone that has this issue could try moving `scope.sh` out of the way to see if that's just the issue.

**Comment by comraderayane** [comment]
Just copied the new ``scope.sh`` and ``rc.conf`` to my config directory, and ranger no longer crashes in normal mode. In debug mode, I get this error when trying to preview an image:
```
ranger version: ranger-master 1.9.0
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: en_US.UTF-8
Current file: 'somefile.jpg'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 394, in loop
    ui.draw_images()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 402, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 115, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/lib/python3.6/site-packages/ranger/core/actions.py", line 166, in notify
    raise obj
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 111, in draw_image
    self.wid, self.hei)
  File "/usr/lib/python3.6/site-packages/ranger/ext/img_display.py", line 119, in draw
    input_gen = self._generate_w3m_input(path, start_x, start_y, width, height)
  File "/usr/lib/python3.6/site-packages/ranger/ext/img_display.py", line 158, in _generate_w3m_input
    fontw, fonth = self._get_font_dimensions()
  File "/usr/lib/python3.6/site-packages/ranger/ext/img_display.py", line 108, in _get_font_dimensions
    xpixels, ypixels = int(output[0]), int(output[1])
IndexError: list index out of range
```

**Comment by toonn** [comment]
Thanks for the debug output. Note that you no longer need scope and rc unless you customize them.

**Comment by PhilipNelson5** [comment]
Good news, replacing `scope.sh` with the newest one that @toonn mentioned fixed the image preview! However, the preview renders out of the boundary...
![picture](https://user-images.githubusercontent.com/19827319/36272632-4ee6c06a-123f-11e8-8081-3c00fa1616f6.png)
.

**Comment by zapdee** [comment]
had the same issue, but replacing my `scope.sh` with the current github version fixed that error entirely

**Comment by toonn** [comment]
Note that you no longer need a `scope.sh` at all unless you intend to customize it. I think it's not necessary to remove/comment out the `set preview_script ~/.config/ranger/scope.sh` line in `rc.conf` but you might as well.

**Comment by zapdee** [comment]
> Note that you no longer need a scope.sh at all unless you intend to customize it. I think it's not necessary to remove/comment out the set preview_script ~/.config/ranger/scope.sh line in rc.conf but you might as well.

I didn't know. I'll try that immediately. Cheers, mate!

**Comment by toonn** [comment]
Seems like you do need to comment out or remove the `set preview_script` line.
@zapdee, could you check whether there's a similar issue already and if not open a new one on this?

**Comment by toonn** [comment]
This issue has accumulated several not directly related reports and has therefore gotten unwieldy. Since the original problem was fixed I'm closing this. Please open up seperate issues for all remaining problems, we really appreciate the reports.

**Comment by brburzon** [comment]
Thanks a lot! Renaming `~/.config/ranger/scope.sh` to `~/.config/ranger/scope_backup.sh` and commenting out the `set preview_script` worked for me.
