### ISSUE TITLE
ranger compiled from git commit f855979 crashes when I press Ctrl+Space in rename prompt.

### ISSUE THREAD

**Issue by crocket** [ranger/ranger#1113]
#### Runtime Environment

- Operating system and version: Gentoo Linux
- Terminal emulator and version: x11-terms/st-0.7
- Python version: dev-lang/python-3.5.4-r1
- Ranger version/commit: git commit f855979
- Locale: en_US.utf8

#### Current Behavior

In rename prompt, Ctrl+Space crashes ranger.

#### Expected Behavior

Ctrl+Space shouldn't crash ranger.

#### Steps to reproduce

1. Press `I`, `a`, or `A` to launch a rename prompt
2. Press `Ctrl+Space`

#### Traceback

```
$ ranger
ranger version: ranger-master 1.9.1
Python version: 3.5.4 (default, Jan  9 2018, 08:23:30) [GCC 6.4.0]
Locale: en_US.UTF-8
Current file: '/dev'

Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib64/python3.5/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib64/python3.5/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib64/python3.5/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib64/python3.5/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib64/python3.5/site-packages/ranger/gui/widgets/console.py", line 111, in draw
    self.addstr(0, len(self.prompt), str(line[x:]))
  File "/usr/lib64/python3.5/site-packages/ranger/gui/curses_shortcuts.py", line 45, in addstr
    self.win.addstr(*_fix_surrogates(args))
ValueError: embedded null character

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by BerkeleyTrue** [comment]
This was fixed shortly after the release of 1.9.1 in https://github.com/ranger/ranger/pull/1091

Any way we can a new release? I'd love to start using ranger again.

**Comment by crocket** [comment]
I compiled ranger from commit f3d8c57b1fa24f0fa8b4c3d2e5f96bf6a2f9778e
The issue still exists in f3d8c57b1fa24f0fa8b4c3d2e5f96bf6a2f9778e

**Comment by toonn** [comment]
I can confirm this is a seperate issue.
@BerkeleyTrue, we're working on a new release, just haven't had much time.

**Comment by toonn** [comment]
The same "solution" would suppress the error but not the cause which is you explecitly entered a NULL, so we'll need to trim that from the input.

**Comment by BerkeleyTrue** [comment]
@toonn understood. :+1:
