### ISSUE TITLE
Ranger crashes on startup

### ISSUE THREAD

**Issue by jaseemabid** [ranger/ranger#1655]
#### Runtime Environment

- Operating system and version: MacOS 
- Terminal emulator and version: Iterm2 3.3
- Python version: Python version: 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
- Ranger version/commit: 1.9.2
- Locale: None.None

#### Current Behavior
Intermittent crashes on startup

#### Expected Behavior
App works as normal

#### Steps to reproduce
1. Occasionally the app crashes on startup, unable to reproduce consistently. 

#### Traceback

```
ranger version: ranger 1.9.2
Python version: 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
Locale: None.None

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/ui.py", line 339, in redraw
    self.finalize()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/ui.py", line 394, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/displayable.py", line 264, in finalize
    displayable.finalize()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/widgets/view_base.py", line 60, in finalize
    - self.main_column.scroll_begin
AttributeError: 'NoneType' object has no attribute 'pointer'
```

**Comment by jaseemabid** [comment]
Update: Can be reproduced with "$ ranger file"

**Comment by toonn** [comment]
Could you try running `env LC_ALL=en_US.UTF-8 ranger --clean`?

**Comment by jaseemabid** [comment]
@toonn Fails the same way. 

```
$ env LC_ALL=en_US.UTF-8 ranger --clean enum.go
ranger version: ranger 1.9.2
Python version: 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
Locale: None.None

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/ui.py", line 339, in redraw
    self.finalize()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/ui.py", line 394, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/displayable.py", line 264, in finalize
    displayable.finalize()
  File "/usr/local/Cellar/ranger/1.9.2/libexec/ranger/gui/widgets/view_base.py", line 60, in finalize
    - self.main_column.scroll_begin
AttributeError: 'NoneType' object has no attribute 'pointer'
```

**Comment by toonn** [comment]
Oh, you're passing a file. That was broken in the release. It should be fixed on master though.

**Comment by usmcamp0811** [comment]
I've got the same problem. 

System:
Manjaro
Python 3.7
Terminator 1,9-6

```
 19:43:07  ~  ranger   master 
 mcamp  Redhorse  $  ranger
ranger version: ranger-master 
Python version: 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 131, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.7/site-packages/ranger/container/bookmarks.py", line 47, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.7/site-packages/ranger/container/bookmarks.py", line 237, in _load_dict
    dct[key] = self.bookmarktype(value)
  File "/usr/lib/python3.7/site-packages/ranger/container/directory.py", line 150, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

running `ranger --clean` does launch ranger. I have tried reinstalling and that didn't fix it.

**Comment by toonn** [comment]
@usmcamp0811, that's a different issue, you're starting ranger without arguments? Seems like something's wrong with your bookmarks. Could you open up a new issue, maybe include your bookmarks?

**Comment by toonn** [comment]
Thought I'd verify my claim. This has *not* been fixed on master yet.

**Comment by goodboy** [comment]
@toonn just came across this (by accident) as well by passing a file at startup.

**Comment by toonn** [comment]
Yep, like I said it has *not* been fixed yet. Thanks for confirming.
