### ISSUE TITLE
Need to run unbookmark command twice

### ISSUE THREAD

**Issue by mightbered** [ranger/ranger#1749]
- Operating system and version: Void Linux x86_64
- Terminal emulator and version: URxvt 9.22
- Python version: Python 3.6.9
- Ranger version/commit: ranger 1.9.2

#### Current Behavior
When trying to remove a file from bookmarks, I need to run two `um<key>` commands before it gets removed, also, why is it when I try to bookmark a file it says `no bookmarked defined for <key>`?

#### Expected Behavior
Should be able to remove a file from the bookmarks by using `um<key> once, also to not display that `no bookmark defined for <key>` when you are just in the process of setting one.

#### Context
New users (like me) find it annoying to have to run the command twice, and also having that `no bookmarked defined for <key>` can also mislead new users (like me).

#### Steps to reproduce
1. Try to bookmark a file using `m<key>`
2. You will get a message `no bookmarked defined for <key>`
3. Now try to remove the bookmark using `um<key>`
4. Open the bookmarks using `'`
5. You will still see your bookmark in the list

**Comment by Vifon** [comment]
Indeed it seems to be the case on 1.9.2. I cannot reproduce it on `master` though, so it should be fixed in the next release. In the meanwhile consider installing ranger from the `master` Git branch

**Comment by mightbered** [comment]
Um... Weirdly I still need to unbookmark files twice, installed ranger from `master`

**Comment by toonn** [comment]
I can confirm this is still an issue on master. Playing around I also sometimes had to `m<any>` twice to *create* the bookmark in the first place.

**Comment by leipengkai** [comment]
I have a similar problem and it has not been solved yet

**Comment by hut** [comment]
Can't reproduce.
