### ISSUE TITLE
fasd integration command causes ranger to crash

### ISSUE THREAD

**Issue by NetherKing1357** [ranger/ranger#1956]
#### Runtime Environment
- Operating system and version: Ubuntu 18.04.4
- Terminal emulator and version: gnome-terminal 3.28.2
- Python version: 2.7.17
- Ranger version/commit: ranger-master
- Locale: None.None
- Shell: zsh

#### Current Behavior
Adding the text provided at https://github.com/ranger/ranger/wiki/Custom-Commands#fasd to commands.py causes ranger to crash on attempt to open.

I've already tried adding the logging plugin as instructed at https://github.com/ranger/ranger/wiki/Integration-with-other-programs#fasd . It does not help.

ranger -c works fine.

Will attach commands.py if it is required in a comment to the issue.

#### Steps to reproduce
1. Install fasd from universe repo
2. Copy and paste the given code into commands.py
3. Attempt to open ranger

#### Traceback

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 121, in main
    load_settings(fm, args.clean)
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 426, in load_settings
    load_custom_commands(system_comm_path, custom_comm_path)
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 413, in load_custom_commands
    custom_comm_path)
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 402, in import_file
    module = imp.load_source(name, path)
  File "/home/USER/.config/ranger/commands.py", line 139
    def tab(self, tabnum: int):
                        ^
SyntaxError: invalid syntax
```

**Comment by toonn** [comment]
I guess someone added type annotations which aren't supported by python 2.7. I fixed up the two occurrences. Try again with the current code on the wiki?

**Comment by NetherKing1357** [comment]
Thank you for the quick reply!
No longer crashes at declaration of tab(), but still crashes at output
Traceback
```
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 121, in main
    load_settings(fm, args.clean)
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 426, in load_settings
    load_custom_commands(system_comm_path, custom_comm_path)
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 413, in load_custom_commands
    custom_comm_path)
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 402, in import_file
    module = imp.load_source(name, path)
  File "/home/USER/.config/ranger/commands.py", line 147
    output = subprocess.check_output(["fasd", "-dl", *args], universal_newlines=True)
                                                     ^
SyntaxError: invalid syntax
```

**Comment by NetherKing1357** [comment]
Removing *args allows allows ranger to run and the jump functionality seems to work fine. Probably another Python 2.7 issue. Does it break anything I should be worried about? If not, I will close the issue.

**Comment by toonn** [comment]
Updated that bit as well. Could you try again? Maybe the args pass the configuration files or something? I don't see why fasd wouldn't behave the same as long as you're running ranger under the same user.

**Comment by NetherKing1357** [comment]
The exact code you posted threw up a cannot catenate list to tuple error. This worked:
```
class fasd(Command):
    """
    :fasd

    Jump to directory using fasd
    """
    def execute(self):
        args = self.rest(1).split()
        if args:
            directories = self._get_directories(*args)
            if directories:
                self.fm.cd(directories[0])
            else:
                self.fm.notify("No results from fasd", bad=True)

    def tab(self, tabnum):
        start, current = self.start(1), self.rest(1)
        for path in self._get_directories(*current.split()):
            yield start + path

    @staticmethod
    def _get_directories(*args):
        import subprocess
        output = subprocess.check_output(["fasd", "-dl"] + list(args), universal_newlines=True)
        dirs = output.strip().split("\n")
        dirs.sort(reverse=True)  # Listed in ascending frecency
        return dirs
```
(converted args into list and catenated)
Closing issue, thank you for the support!

**Comment by toonn** [comment]
Oh, good, didn't really pay too much attention tbh. Will you fix the wiki as well or should I?

**Comment by raghavmallampalli** [comment]
Fixed in the wiki.
