### ISSUE TITLE
Browser-based Email Client - replace built-in file manager when attaching files?

### ISSUE THREAD

**Issue by philiprhoades** [ranger/ranger#2077]
People,

I am not sure if this is possible but I would like to extend the space where I use Ranger to everything I do that makes use of some sort of File Manager - eg in RoundCubeMail, when I want to attach a file, in FireFox I click on the paperclip and a file manager-like GUI interface pops up - is there anyway to config FF so that it brings up Ranger and then Ranger allows me to select the file(s) name(s) to return to RCM for attaching to the email?

Thanks,
Phil.

**Comment by toonn** [comment]
I'm not sure you can replace the file picker dialog. I remember talk about this recently probably on the subreddit, r/ranger.

**Comment by NoSuck** [comment]
This is a shortcoming of Firefox.  If you use a *real* mail client, however, try `ranger --choosefile=/tmp/attach` or even just copying paths to the clipboard, depending on how the mail client operates.

**Comment by toonn** [comment]
@GermainZ recently implemented a Dbus service for this IIRC. That might be perfect in this scenario.

**Comment by GermainZ** [comment]
I implemented an xdg-desktop-portal backend for the FileChooser portal, which can make use of ranger. More info here: [xdg-desktop-portal-termfilechooser](https://github.com/GermainZ/xdg-desktop-portal-termfilechooser). If you're using Arch, I also added [a package to the AUR](https://aur.archlinux.org/packages/xdg-desktop-portal-termfilechooser-git/).

Note that it will only be called if `XDG_CURRENT_DESKTOP` is set to one of `i3;wlroots;sway;Wayfire;river;mate;lxde;openbox;unity;pantheon` for now. You must also launch Firefox with `GTK_USE_PORTAL=1 firefox`.

I am using this with Firefox (v90) successfully.
It should also work with other programs that use gtk3's GtkFileChooserNative (not sure about other toolkits).
I'm not sure how it works if you happen to have other portal backends installed.

P.S. For issues/comments related to xdg-desktop-portal-termfilechooser, please use the linked repo.

**Comment by philiprhoades** [comment]
@GermainZ ,

Ah interesting!  I am just upgrading to Fedora 34 KDE with Wayland and Plasma . . so still no luck with that DE but at least I know it might be possible in the future . . 

Thanks!
