### ISSUE TITLE
preview image with terminator

### ISSUE THREAD

**Issue by ri-aje** [ranger/ranger#2079]
#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
ranger version: ranger-master v1.9.3-143-g6a0c6b09
Python version: 3.7.1 (default, Sep 21 2019, 10:53:58) [GCC 7.4.0]
Locale: en_US.UTF-8
- Locale: 

this is more of a question than bug or issue, so I will skip the boilerplate. I wonder does ranger image preview work with the terminator terminal? I checked out ranger's comments in rc.conf, which talks about iterm2, terminology, urxvt, etc. they all worked by directly preview image in the terminal. I use terminator most of the time, so I am trying to see if full color image preview is doable. if so, how? and if not, why? thanks for any explanations. I searched issues here, but cannot seem to find a similar discussion in history.

**Comment by toonn** [comment]
I think some people have success with w3m but that's more of an accidental thing really. It's written for XTerm and very few terminals properly emulate XTerm.

Why don't we support all terminals? Because many terminals don't support displaying images at all, all the methods except kitty, terminology and iterm2 are hacks. Only general protocol we're still missing is sixel.

**Comment by planet36** [comment]
Image previews in Terminator (or any VTE terminal) don't work for me either.

`terminator -v`
> terminator 2.0.1

`ranger --version`
> ranger version: ranger 1.9.3
> Python version: 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
> Locale: en_US.UTF-8

`w3m -version`
> w3m version w3m/0.5.3+git20200507, options lang=en,m17n,image,color,ansi-color,mouse,gpm,menu,cookie,ssl,ssl-verify,external-uri-loader,nntp,ipv6,alarm,mark

> ueberzug 18.1.6-2

I've tried both `set preview_images_method ueberzug` and `set preview_images_method w3m`, and nothing works except the `kitty` terminal.

**Comment by toonn** [comment]
Ueberzug should work since it doesn't rely on your terminal at all. Does require X11 and installing ueberzug, of course.

**Comment by planet36** [comment]
> Ueberzug should work since it doesn't rely on your terminal at all. Does require X11 and installing ueberzug, of course.

My `.config/ranger/rc.conf` is
> set preview_images true
> set preview_images_method ueberzug

I'm using xorg-server 1.20.9-2, dwm 6.2 (no patches).  I've tried with and without xcompmgr, and there are no image previews.

**Comment by toonn** [comment]
And you installed the right ueberzug? I.e., the tests from the ueberzug readme work?

**Comment by planet36** [comment]
> And you installed the right ueberzug? I.e., the tests from the ueberzug readme work?

I used pacman to install it.

`sudo pacman -S --needed ueberzug`
> warning: ueberzug-18.1.6-2 is up to date -- skipping
>  there is nothing to do

I don't see any tests in https://github.com/seebye/ueberzug/blob/master/README.md

Should I install it with pip instead?

**Comment by ri-aje** [comment]
> > And you installed the right ueberzug? I.e., the tests from the ueberzug readme work?
> 
> I used pacman to install it.
> 
> `sudo pacman -S --needed ueberzug`
> 
> > warning: ueberzug-18.1.6-2 is up to date -- skipping
> > there is nothing to do
> 
> I don't see any tests in https://github.com/seebye/ueberzug/blob/master/README.md
> 
> Should I install it with pip instead?

just a data point, I installed with pip. it then works out of the box, with the preview setting, of course.

**Comment by toonn** [comment]
The examples are what I meant.
So this is solved? Maybe report to the arch package maintainer that the package is broken.

**Comment by planet36** [comment]
> just a data point, I installed with pip. it then works out of the box, with the preview setting, of course.

@ri-aje, which window manager are you using?

**Comment by planet36** [comment]
> The examples are what I meant.
> So this is solved? Maybe report to the arch package maintainer that the package is broken.

Previews still don't appear with the pip ueberzug installed.

Is there a way for ueberzug to print diagnostics on what it's doing?  I can see the CPU go up momentarily when the image is selected in ranger, so I guess something is happening underneath.

`ranger --debug` doesn't print anything.

**Comment by toonn** [comment]
@planet36, I think you should open an issue over on the ueberzug tracker. Get that working first then come back if it still doesn't work in ranger.

**Comment by ri-aje** [comment]
> > just a data point, I installed with pip. it then works out of the box, with the preview setting, of course.
> 
> @ri-aje, which window manager are you using?

xfce. does it matter? I thought it only requires x11.

**Comment by planet36** [comment]
@toonn Agreed.  I'll try to narrow down the problem.

**Comment by seebye** [comment]
@planet36  **If** you use fish as shell: they modify information provided by your terminal emulator.   
    They stopped doing it https://github.com/fish-shell/fish-shell/commit/d5a239e59ec0e84a47d499270f618e432abd747f,  
    but there isn't a release which contains the commit yet.  
    So if you use fish you have the option to either compile fish from source or to use another shell.

**Comment by planet36** [comment]
@seebye Yes, I do use fish.  That explains it.  Thanks!
