### ISSUE TITLE
Error  No such file or directory: 'screen'

### ISSUE THREAD

**Issue by LeducH** [ranger/ranger#2272]
#### Runtime Environment

- Operating system and version: (BTW) Arch Linux x86_64 
- Terminal emulator and version: termite v15
- Python version: Python 3.9.2
- Ranger version/commit: in Traceback
- Locale: in Traceback
- WM: bspwm

#### Current Behavior
Ranger does not start

#### Expected Behavior
Ranger starts 

#### Context

I want to open ranger 

#### Steps to reproduce
1. type 'ranger' in terminal press enter
2. 
3. 

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
Locale: en_IE.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3.9/site-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

```

**Comment by toonn** [comment]
This should be fixed on master, could you check?

**Comment by LeducH** [comment]
no still not working 

```
                  .o+`                   -------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: 20KH0035UK ThinkPad X1 Carbon 6th 
               `+oooooo:                 Kernel: 5.11.11-arch1-1 
               -+oooooo+:                Uptime: 14 hours, 17 mins 
             `/:-:++oooo+:               Packages: 1440 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.8 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           WM: bspwm 
         ./ooosssso++osssssso+`          Theme: Breeze [GTK2/3] 
        .oossssso-````/ossssss+`         Icons: Papirus-Light [GTK2/3] 
       -osssssso.      :ssssssso.        Terminal: termite 
      :osssssss/        osssso+++.       Terminal Font: Envy Code R 14 
     /ossssssss/        +ssssooo/-       CPU: Intel i5-8250U (8) @ 3.400GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: Intel UHD Graphics 620 
  `+sso+:-`                 `.-/+oso:    Memory: 3888MiB / 7488MiB 
 `++:.                           `-/+/
```

```
ranger version: ranger 1.9.3
Python version: 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
Locale: en_IE.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3.9/site-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

```

**Comment by toonn** [comment]
That looks like ranger 1.9.3, not master.

**Comment by nperry** [comment]
can confirm this fixes it using `ranger-git` from AUR.

**Comment by LeducH** [comment]
still open

**Comment by LeducH** [comment]
Why is this closed it still does not work

**Comment by toonn** [comment]
Because it was fixed on master. Issues don't track releases.
