### ISSUE TITLE
Ranger crash while scrolling using mousewheel in leftmost (directory panel)

### ISSUE THREAD

**Issue by pra33g** [ranger/ranger#2460]
#### Runtime Environment

- Operating system and version: Manjaro Linux x86_64 Kernel: 5.13.19
- Terminal emulator and version: Terminator 2.1.1
- Python version: 3.9.7
- Ranger version/commit: ranger-master 
- Locale: en_US.UTF-8

#### Current Behavior
Crash on scrolling using mousewheel inside terminal.
#### Expected Behavior
Crashless behavior.
#### Context

I was scrolling in the directory panel. The rightmost and middle scrolling works fine,
#### Possible Solutions
:\
#### Steps to reproduce
1. Scroll in the lefmost panel. Use a directory where scrolling is available.

#### Traceback

```
ranger version: ranger-master 
Python version: 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 271, in handle_input
    self.handle_mouse()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 197, in handle_mouse
    DisplayableContainer.click(self, event)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/view_base.py", line 188, in click
    if DisplayableContainer.click(self, event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 284, in click
    if displayable.click(event):
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/browsercolumn.py", line 81, in click
    self.fm.move_parent(direction)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 560, in move_parent
    self.thistab.enter_dir(parent.files[parent.pointer + n])
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object is not subscriptable


```

**Comment by toonn** [comment]
How recent is your ranger version? This sounds a lot like something that has been fixed on the master branch. Maybe try running ranger from a checkout of the repository to make sure you're running the latest revision.

**Comment by pra33g** [comment]
>How recent is your ranger version?
```
lveritas in ~ λ ranger --version
ranger version: ranger-master 
Python version: 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
Locale: en_US.UTF-8
```

Apart from this I don't know how answer your question. I have an updated system (rolling release, pacman -Syu).
Also the issue persists still.  
here is a gif. You can see me taking the mouse pointer to leftmost panel. After that it crashes when I scroll.
![rangerIssue](https://user-images.githubusercontent.com/77376446/135607265-d651382f-f000-4c3d-947d-fd10f6ff8a50.gif)

**Comment by toonn** [comment]
Hmm, that should be pretty recent. Could you try cloning the repo and running `ranger.py`, just to make sure? It's very hard to debug something I can't reproduce.

**Comment by jumostedu** [comment]
I'm having the same problem, also on Manjaro. I had a look, it does **not** happen with current master. It seems, manjaro still has ranger at commit 5047d9e5 in their repo, which is a from November 2020, so one year old. I'll try to investigate why that is and how to get them to upgrade it. But this issue can be closed.

@pra33g In the meantime you could just use the repo, or probably even simpler, use https://aur.archlinux.org/packages/ranger-git/ instead of the package from the official repos.

**Comment by jumostedu** [comment]
@toonn The issue might be that there are no more release tags in this repo since v1.9.3 in December 2019, maybe the Arch Linux packager (which Manjaro gets its packages from and which is also as old as the Manjaro package: https://archlinux.org/packages/community/any/ranger/) uses them to trigger new versions. Are there plans to have releases of ranger, or is it just the master branch? Anyway, I'll report the package out of date so they can decide if they update it to a recent master version.

**Comment by toonn** [comment]
Yes, once I have time. Won't be before end of the year unfortunately.

**Comment by jumostedu** [comment]
Ok thanks, then I won't flag the Arch package as outdated. Others on Arch with the same problem can use the AUR package as I mentioned above. But I think you could close this issue.
