### ISSUE TITLE
pandoc from 2.15 onwards hangs on odp/ods files, scope.sh update required

### ISSUE THREAD

**Issue by ngoonee** [ranger/ranger#2594]
#### Runtime Environment

Operating system and version: Arch Linux 
Terminal emulator and version: Tmux in alacritty
ranger version: ranger 1.9.3
Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Locale: en_GB.UTF-8

#### Current Behavior

When trying to preview odp/ods files, ranger's default scope.sh will call pandoc. Since version 2.15 this will fail (huge memory leak) on files pandoc cannot handle, see https://github.com/jgm/pandoc/issues/7973

#### Expected Behavior

Don't call pandoc except on files it can handle (odt is fine, not sure what sxw even is so I haven't tested that).

#### Context
Just normal browsing around the files in my directory, when the cursor moves to an odp/ods file no preview is generated (which wasn't before anyway) but then a process is created which never exits and eventually consumes all RAM (each process eats 100% of one CPU as well)

#### Possible Solutions
Remove at least odp/ods (maybe sxw but I don't know what that is) from scope.sh

#### Steps to reproduce
1. Open ranger
2. Browse to a folder containing an odp or ods type file
3. move cursor to it and watch top/glances.

**Comment by markus-bauer** [comment]
@ngoonee, was this already fixed here https://github.com/ranger/ranger/commit/9da2b4c79323a3f34da8d54198364d549a29ff00 (not tested)?

**Comment by sanfans** [comment]
I have version 1.9.3 (latest) in arch linux (https://wiki.archlinux.org/title/ranger) and the issue still persists

**Comment by RCarlosH** [comment]
I'm using 1.9.3-6 in artix and it still happens with odp files
![screenshot-2023-03-28-195308](https://user-images.githubusercontent.com/110568160/228406682-959c3ef9-41d6-4532-a4a1-1081c377c8dc.png)

**Comment by toonn** [comment]
@sanfans, you can either install `ranger-git` from the AUR or you can make the same change to your `scope.sh`, or copy the one from the repo if you haven't customized it yet.

**Comment by phylor** [comment]
Any chance on releasing a new version? Last version was released in 2019.

Or is the project dead and we should move to another file manager?

If it's not and if the idea is to install it via git, it would be great to mention that somewhere visible.

**Comment by ggio** [comment]
Running version 1.9.4 on Fedora 41 and the issue it’s still there.

**Comment by toonn** [comment]
1.9.4 was a release out of need with a single cherry pick.

1.9.5 is coming, but slowly.
