### ISSUE TITLE
Image preview not working(tried with ueberzug and w3m)

### ISSUE THREAD

**Issue by davidfffff** [ranger/ranger#2826]
Not sure what changed or if it's just me but the image previewing suddenly stop working.

#### Runtime Environment
- Operating system and version: Arch Linux (Linux 6.2.10-arch1-1)
- Terminal emulator and version: alacritty 0.12.0
- Python version: 3.10.10
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior

The place where ranger would usually display the image preview shows nothing. No error messages.

#### Expected Behavior

Image preview showing.

**Comment by toonn** [comment]
Try running Ranger from the master branch. It's possible an issue has been fixed since last release.
Also try an older version of Alacritty and maybe even Python. The most likely cause is something's updated.

**Comment by davidjaur** [comment]
I tried running ranger from the master branch but the issue still remains. Then I tried several of the previous releases of alacritty, python, ueberzug and ranger but no luck. After that I tested with other terminal emulators, urxvt and kitty, both work with w3m but not ueberzug, In alacritty neither work.

**Comment by toonn** [comment]
Every terminal should work with ueberzug, it only requires X11.
If the same Ranger config works for a different terminal then the problem must be Alacritty. It might simply not be compatible with `w3mimagedisplay`. The `iterm2` method is also worth trying, it works in more terminals than just iTerm2.

If Alacritty has SIXEL support you can try the new `sixel` method on the master branch.

**Comment by bitterhalt** [comment]
I got same problem with Alacritty and DWM. In i3 it draws images just fine. This started 2 days ago.

**Comment by davidfffff** [comment]
I found the issue. When importing Xlib in python it was grabbing it from ~/.local/lib/ which for some reason is different than /usr/lib/. The  one in .local does not have the Xlib.ext.shape.SO class which ueberzug needs when trying to draw an image. So I just renamed Xlib to Xlib_ in /.local/lib/ to test it and now it works fine.
